/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/storage/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a presigned URL for file upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GenerateUploadUrlInput"];
                };
            };
            responses: {
                /** @description Upload URL generated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadUrlResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/upload/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload a file to storage */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The encoded file key to upload */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File uploaded successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadSuccess"];
                    };
                };
                /** @description Invalid input or missing file */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a file from storage */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The encoded file key to delete */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description File not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UploadUrlResponse: {
            /**
             * @description The URL to upload the file to
             * @example /api/storage/upload/images%2F1703123456789-my-photo.jpg
             */
            url: string;
            /**
             * @description The unique filename with timestamp
             * @example images/1703123456789-my-photo.jpg
             */
            name: string;
            /**
             * Format: uri
             * @description The public URL to access the file after upload
             * @example https://pub-xxx.r2.dev/images/1703123456789-my-photo.jpg
             */
            publicUrl: string;
        };
        ErrorResponse: {
            /** @example Error message */
            error: string;
            /** @example 400 */
            statusCode: number;
            details?: unknown;
        };
        GenerateUploadUrlInput: {
            /**
             * @description The filename with optional folder path
             * @example images/my-photo.jpg
             */
            filename: string;
            /**
             * @description The MIME type of the file
             * @example image/jpeg
             */
            contentType: string;
        };
        UploadSuccess: {
            /** @example true */
            success: boolean;
            /** @example images/1703123456789-my-photo.jpg */
            key: string;
            /**
             * Format: uri
             * @example https://pub-xxx.r2.dev/images/1703123456789-my-photo.jpg
             */
            publicUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
