/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users in account */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sortBy?: string;
                    sortOrder?: "ASC" | "DESC";
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of users */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["PaginatedUsers"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create user-account relationships in bulk
         * @description Assigns multiple users to accounts with specified roles. Requires MANAGER role or higher.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BulkUserAccountsInput"];
                };
            };
            responses: {
                /** @description User accounts created successfully */
                201: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["BulkOperationSuccess"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - requires MANAGER role or higher */
                403: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Delete user-account relationships in bulk
         * @description Removes multiple users from accounts. Requires MANAGER role or higher.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BulkUserAccountsInput"];
                };
            };
            responses: {
                /** @description User accounts deleted successfully */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["BulkOperationSuccess"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - requires MANAGER role or higher */
                403: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User details */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            data: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete user (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User deleted */
                204: {
                    headers: Record<string, unknown>;
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update user */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserInput"];
                };
            };
            responses: {
                /** @description User updated */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            data: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a soft-deleted user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User restored successfully */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            data: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - requires ADMIN role */
                403: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found or not deleted */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sortBy?: string;
                    sortOrder?: "ASC" | "DESC";
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of accounts */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["PaginatedAccounts"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create new account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAccountInput"];
                };
            };
            responses: {
                /** @description Account created */
                201: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            data: components["schemas"]["Account"];
                        };
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - Super admin only */
                403: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Domain already exists */
                409: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account details */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            data: components["schemas"]["Account"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Account not found */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete account (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account deleted */
                204: {
                    headers: Record<string, unknown>;
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - Super admin only */
                403: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Account not found */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update account */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateAccountInput"];
                };
            };
            responses: {
                /** @description Account updated */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            data: components["schemas"]["Account"];
                        };
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Account not found */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Domain already exists */
                409: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/accounts/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a soft-deleted account
         * @description Restores a soft-deleted account. Only super-admin.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account restored successfully */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            data: components["schemas"]["Account"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - Super admin only */
                403: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Account not found or not deleted */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending invitations
         * @description Lists all pending (not accepted, not expired) invitations for the account
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of pending invitations */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                /** Format: email */
                                email: string;
                                role: string;
                                expiresAt: string;
                                createdAt: string;
                                invitedBy: {
                                    id: string;
                                    name: string;
                                };
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create invitation or link existing user
         * @description Invites a new user via email or links an existing user immediately
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description Email address to invite
                         */
                        email: string;
                        /**
                         * @description Role to assign (cannot exceed your own role)
                         * @enum {string}
                         */
                        role: "ADMIN" | "MANAGER" | "EDITOR" | "AUTHOR" | "VIEWER" | "BILLING" | "ANALYTICS";
                    };
                };
            };
            responses: {
                /** @description User linked or invitation sent */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": {
                            linked: boolean;
                            invited: boolean;
                            user?: {
                                id: string;
                                email: string;
                                name: string;
                            };
                            invitation?: {
                                id: string;
                                email: string;
                                role: string;
                                expiresAt: string;
                            };
                        };
                    };
                };
                /** @description Cannot assign role higher than own */
                403: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User already in account or pending invitation exists */
                409: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke invitation
         * @description Cancels a pending invitation
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invitation revoked */
                204: {
                    headers: Record<string, unknown>;
                    content?: never;
                };
                /** @description Invitation not found */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit logs
         * @description Returns paginated audit logs filtered by entity, entityId, or action. Requires ADMIN role or ANALYTICS role.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    /** @description Filter by entity type (e.g., User, Account) */
                    entity?: string;
                    /** @description Filter by entity ID */
                    entityId?: string;
                    /** @description Filter by action type */
                    action?: "INSERT" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "SIGNUP" | "TOKEN_REFRESH" | "LOGIN_FAILED";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of audit logs */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["PaginatedAuditLogs"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - requires ADMIN or ANALYTICS role */
                403: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a presigned URL for file upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GenerateUploadUrlInput"];
                };
            };
            responses: {
                /** @description Upload URL generated successfully */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["UploadUrlResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/upload/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload a file to storage */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The encoded file key to upload */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File uploaded successfully */
                200: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["UploadSuccess"];
                    };
                };
                /** @description Invalid input or missing file */
                400: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a file from storage */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The encoded file key to delete */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File deleted successfully */
                204: {
                    headers: Record<string, unknown>;
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description File not found */
                404: {
                    headers: Record<string, unknown>;
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example John Doe */
            name: string;
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "inactive";
            /** @example false */
            isSuperAdmin: boolean;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00Z
             */
            updatedAt: string;
        };
        PaginationMeta: {
            /** @example 1 */
            currentPage: number;
            /** @example 50 */
            limit: number;
            /** @example 100 */
            totalItems: number;
            /** @example 2 */
            totalPages: number;
            /** @example false */
            hasPreviousPage: boolean;
            /** @example true */
            hasNextPage: boolean;
        };
        PaginatedUsers: {
            data: components["schemas"]["User"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        ErrorResponse: {
            /** @example Error message */
            error: string;
            /** @example 400 */
            statusCode: number;
            details?: unknown;
        };
        BulkOperationSuccess: {
            /** @example true */
            success: boolean;
            /**
             * @description Number of records affected
             * @example 3
             */
            count: number;
        };
        UserAccount: {
            /**
             * Format: uuid
             * @description The ID of the user
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            userId: string;
            /**
             * Format: uuid
             * @description The ID of the account
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            accountId: string;
            /**
             * @description The role of the user in the account
             * @example VIEWER
             * @enum {string}
             */
            role: "ADMIN" | "MANAGER" | "EDITOR" | "AUTHOR" | "VIEWER" | "BILLING" | "ANALYTICS";
        };
        BulkUserAccountsInput: components["schemas"]["UserAccount"][];
        UpdateUserInput: {
            /** @example Updated Name */
            name?: string;
            /**
             * @example active
             * @enum {string}
             */
            status?: "active" | "inactive";
        };
        Account: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @example Acme Corp */
            name: string;
            /** @example Main business account */
            description: string | null;
            /** @example acme.com */
            domain: string | null;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00Z
             */
            updatedAt: string;
        };
        PaginatedAccounts: {
            data: components["schemas"]["Account"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateAccountInput: {
            /** @example New Account */
            name: string;
            /** @example Account description */
            description?: string;
            /** @example example.com */
            domain?: string;
        };
        UpdateAccountInput: {
            /** @example Updated Name */
            name?: string;
            /** @example Updated description */
            description?: string;
            /** @example updated.com */
            domain?: string;
        };
        AuditLog: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @example 0192abc1-def0-7890-abcd-ef1234567890 */
            transactionId: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            accountId: string | null;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440002
             */
            userId: string | null;
            /** @example User */
            entity: string;
            /** @example 550e8400-e29b-41d4-a716-446655440003 */
            entityId: string;
            /**
             * @example UPDATE
             * @enum {string}
             */
            action: "INSERT" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "SIGNUP" | "TOKEN_REFRESH" | "LOGIN_FAILED";
            /**
             * @example {
             *       "name": "John Doe",
             *       "status": "active"
             *     }
             */
            changes: Record<string, unknown> | null;
            /** @example 192.168.1.1 */
            ipAddress: string | null;
            /** @example Mozilla/5.0... */
            userAgent: string | null;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00Z
             */
            timestamp: string;
        };
        PaginatedAuditLogs: {
            data: components["schemas"]["AuditLog"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        UploadUrlResponse: {
            /**
             * @description The URL to upload the file to
             * @example /api/storage/upload/images%2F1703123456789-my-photo.jpg
             */
            url: string;
            /**
             * @description The unique filename with timestamp
             * @example images/1703123456789-my-photo.jpg
             */
            name: string;
            /**
             * Format: uri
             * @description The public URL to access the file after upload
             * @example https://pub-xxx.r2.dev/images/1703123456789-my-photo.jpg
             */
            publicUrl: string;
        };
        GenerateUploadUrlInput: {
            /**
             * @description The filename with optional folder path
             * @example images/my-photo.jpg
             */
            filename: string;
            /**
             * @description The MIME type of the file
             * @example image/jpeg
             */
            contentType: string;
        };
        UploadSuccess: {
            /** @example true */
            success: boolean;
            /** @example images/1703123456789-my-photo.jpg */
            key: string;
            /**
             * Format: uri
             * @example https://pub-xxx.r2.dev/images/1703123456789-my-photo.jpg
             */
            publicUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
